version: '3.8'
services:
  dev-db:
    image: postgres:14
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clv@123
      POSTGRES_DB: nest_graphql
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
